### ISSUE TITLE
Through error on 8.x

### ISSUE THREAD

**Issue by Sheikh-Alvee** [messente/messente-api-php#13]
- Root composer.json requires messente/messente-api-php ^1.4 -> satisfiable by messente/messente-api-php[1.4.0].
- messente/messente-api-php 1.4.0 requires guzzlehttp/guzzle ^6.2 -> found guzzlehttp/guzzle[6.2.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

**Comment by UkuLoskit** [comment]
Hello! This issue has been fixed in the latest version (1.4.1).

Thank you for your report!
